Repository IBM/ibm-monitoring-prometheus-operator-ext, pull requests merged in 2020-04, with the labels that each got.

#7 add dependency request and add healthcheck dependency annotation
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.1/ibm-monitoring-prometheus-operator-ext.v1.8.1.clusterserviceversion.yaml
  pkg/controller/prometheusext/model/constants.go
Labels: size/M

#9 update for ibm certification
  deploy/crds/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_prometheusext_cr.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/ibm-monitoring-prometheus-operator-ext.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.1/ibm-monitoring-prometheus-operator-ext.v1.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.1/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: size/L

#11 rename csv from 1.8.1 to 1.9.0
  Makefile
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  version/version.go
Labels: size/S

#12 remove default imagePullSecrets
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
Labels: size/XS

#13 enable using sha for image reference
  deploy/crds/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  pkg/apis/monitoring/v1alpha1/prometheusext_types.go
  pkg/controller/prometheusext/model/alertmanager.go
  pkg/controller/prometheusext/model/prometheus.go
Labels: size/M
