Repository IBM/ibm-monitoring-prometheus-operator-ext, pull requests merged in 2020-05, with the labels that each got.

#14 use Env vars for image SHAs; remove dependency on exporter API; roll back CRD change
  cmd/manager/main.go
  deploy/crds/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_prometheusext_cr.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/operator.yaml
  go.mod
  pkg/apis/monitoring/v1alpha1/prometheusext_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/prometheusext/model/alertmanager.go
  pkg/controller/prometheusext/model/common.go
  pkg/controller/prometheusext/model/constants.go
  pkg/controller/prometheusext/model/mcmctl.go
  pkg/controller/prometheusext/model/prometheus.go
  pkg/controller/prometheusext/model/prometheus_operator_deployment.go
  pkg/controller/prometheusext/model/router.go
  pkg/controller/prometheusext/prometheusext_controller.go
  pkg/controller/prometheusext/reconsiler/readstates.go
  pkg/controller/prometheusext/reconsiler/reconsiler.go
  pkg/controller/prometheusext/reconsiler/syncPrometheus.go
Labels: size/L

#15 update productVersion of metering annotation to 3.4.0
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/prometheusext/model/common.go
Labels: size/XS

#16 update operand images
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S

#17 Operand image update - management ingress and prometheus controller
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#18 update default Resources; watch all namespaces for rules
  pkg/controller/prometheusext/model/alertmanager.go
  pkg/controller/prometheusext/model/prometheus.go
Labels: size/M

#20 update for ibm certification
  deploy/crds/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_prometheusext_cr.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/ibm-monitoring-prometheus-operator-ext.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/prometheusext/model/alertmanager.go
  pkg/controller/prometheusext/model/common.go
  pkg/controller/prometheusext/model/constants.go
  pkg/controller/prometheusext/model/mcmctl.go
  pkg/controller/prometheusext/model/prometheus.go
  pkg/controller/prometheusext/model/prometheus_operator_deployment.go
Labels: size/M

#21 add beta channel
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
Labels: size/XS

#22 fix grafana helm release dashboard issue
  pkg/controller/prometheusext/model/constants.go
Labels: size/XS

#23 Beta channel
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.0/ibm-monitoring-prometheus-operator-ext.v1.9.0.clusterserviceversion.yaml
Labels: size/XS

#24 add scripts to protect csv not changed. only dev csv can be changed
  common/scripts/.githooks/pre-commit
  common/scripts/csv-protect.py
  common/scripts/push-csv.sh
Labels: size/L

#26 fix operator2operator upgrade issue - not to update selector label
  pkg/controller/prometheusext/model/mcmctl.go
Labels: size/S

#27 get cluster host url from configmap only
  pkg/controller/prometheusext/reconsiler/commons.go
Labels: size/S

#28 power needs more memory
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.1/ibm-monitoring-prometheus-operator-ext.v1.9.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/prometheusext/model/prometheus_operator_deployment.go
Labels: size/S

#25 improve CSV description and readme with template
  README.md
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.1/ibm-monitoring-prometheus-operator-ext.v1.9.1.clusterserviceversion.yaml
Labels: lgtm, size/M

#29 Beta 1.9.1
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.1/ibm-monitoring-prometheus-operator-ext.v1.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
Labels: size/XS
