Repository IBM/ibm-monitoring-prometheus-operator-ext, pull requests merged in 2020-11, with the labels that each got.

#44 fix typo
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.4/ibm-monitoring-prometheus-operator-ext.v1.9.4.clusterserviceversion.yaml
  deploy/role.yaml
Labels: size/XS

#45 fix scc issue
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.4/ibm-monitoring-prometheus-operator-ext.v1.9.4.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  pkg/controller/prometheusext/model/scc.go
  pkg/controller/prometheusext/reconsiler/reconsiler.go
Labels: size/M

#46 bump up version; use issuer instead of clusterissuer
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.5/ibm-monitoring-prometheus-operator-ext.v1.9.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.5/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  deploy/role.yaml
  pkg/controller/prometheusext/model/cert.go
  version/version.go
Labels: size/XL

#47 update prometheus job relable rules to add namespace and pod label to…
  pkg/controller/prometheusext/model/constants.go
Labels: size/S

#48 update image digest for management ingress
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.5/ibm-monitoring-prometheus-operator-ext.v1.9.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#49 update image digest
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.5/ibm-monitoring-prometheus-operator-ext.v1.9.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S

#50 update management ingress image
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.5/ibm-monitoring-prometheus-operator-ext.v1.9.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#51 URL gets encodes after upgrading Grafana to 7.1.5 and it breaks helm dashboard
  pkg/controller/prometheusext/model/constants.go
Labels: size/XS

#52 use label kubernetes.io/arch
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.5/ibm-monitoring-prometheus-operator-ext.v1.9.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S
