Repository IBM/ibm-monitoring-prometheus-operator-ext, pull requests merged in 2020-03, with the labels that each got.

#2 Install Prometheus operator by creating deployment directly instead of using OLM
  deploy/crds/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_prometheusext_cr.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/ibm-monitoring-prometheus-operator-ext.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  pkg/apis/monitoring/v1alpha1/prometheusext_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/prometheusext/model/mcmctl.go
  pkg/controller/prometheusext/model/prometheus_operator_deployment.go
  pkg/controller/prometheusext/reconsiler/readstates.go
  pkg/controller/prometheusext/reconsiler/reconsiler.go
  pkg/controller/prometheusext/reconsiler/syncPrometheusOperator.go
Labels: size/XL

#3 auto discovery storage class
  deploy/crds/monitoring.operator.ibm.com_v1alpha1_prometheusext_cr.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/ibm-monitoring-prometheus-operator-ext.v1.8.0.clusterserviceversion.yaml
  pkg/controller/prometheusext/model/alertmanager.go
  pkg/controller/prometheusext/model/constants.go
  pkg/controller/prometheusext/model/prometheus.go
  pkg/controller/prometheusext/prometheusext_controller.go
  pkg/controller/prometheusext/reconsiler/commons.go
  pkg/controller/prometheusext/reconsiler/reconsiler.go
Labels: size/M

#4 grafana failed to get metrics from prometheus on ocp 4.4
  pkg/controller/prometheusext/model/alertmanager.go
  pkg/controller/prometheusext/model/constants.go
  pkg/controller/prometheusext/model/prometheus.go
Labels: size/S

#5 remove replace packge in csv
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.8.0/ibm-monitoring-prometheus-operator-ext.v1.8.0.clusterserviceversion.yaml
Labels: size/XS
