Repository IBM/ibm-monitoring-prometheus-operator-ext, pull requests merged in 2021-06, with the labels that each got.

#80 fix cv linter issue:CSVHasValidRelatedImages
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.11.0/ibm-monitoring-prometheus-operator-ext.v1.11.0.clusterserviceversion.yaml
Labels: size/S

#81 add OWNERS file
  OWNERS
Labels: size/XS

#82 Copyright year updated #45123
  Makefile
  pkg/controller/prometheusext/prometheusext_controller.go
  version/version.go
Labels: approved, lgtm, size/XS

#83 increment operator version
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.12.0/ibm-monitoring-prometheus-operator-ext.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.12.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  version/version.go
Labels: approved, size/XL

#84 release-cd merge to master
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.12.0/ibm-monitoring-prometheus-operator-ext.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.12.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  version/version.go
Labels: approved, size/XL
