Repository IBM/ibm-monitoring-prometheus-operator-ext, pull requests merged in 2021-02, with the labels that each got.

#55 update v3 channel
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.0/ibm-monitoring-prometheus-operator-ext.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  version/version.go
Labels: size/S

#56 fix cve-2021-3121
  go.mod
  go.sum
Labels: size/M

#58 update images except initcontainer and ingress
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.0/ibm-monitoring-prometheus-operator-ext.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/S

#59 fix config reload issue and update initcontainer image
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.0/ibm-monitoring-prometheus-operator-ext.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#60 update prometheus controller for protobuf issue
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.0/ibm-monitoring-prometheus-operator-ext.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#61 Security issues
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/ibm-monitoring-prometheus-operator-ext.v1.9.6.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  version/version.go
Labels: size/XL

#63 bump operator version and update icp-management-ingress digest
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.1/ibm-monitoring-prometheus-operator-ext.v1.10.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.10.1/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XL

#64 Update manifest-tool version
  Makefile
Labels: size/XS
