Repository IBM/ibm-monitoring-prometheus-operator-ext, pull requests merged in 2021-04, with the labels that each got.

#72 2.5.11 version of icp-management-ingress digest updated
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/ibm-monitoring-prometheus-operator-ext.v1.9.6.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#73 refresh ingress digest
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/ibm-monitoring-prometheus-operator-ext.v1.9.6.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#75 updated images with vascans fixes
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.9.6/ibm-monitoring-prometheus-operator-ext.v1.9.6.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: lgtm, size/S

#76 operand auto sha update+bump version
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.11.0/ibm-monitoring-prometheus-operator-ext.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.11.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: lgtm, size/XL
