Repository IBM/ibm-monitoring-prometheus-operator-ext, pull requests merged in 2021-07, with the labels that each got.

#87 CRD description updated for recertification
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.12.0/ibm-monitoring-prometheus-operator-ext.v1.12.0.clusterserviceversion.yaml
Labels: approved, size/XS

#88 crd descriptions updated
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.12.0/ibm-monitoring-prometheus-operator-ext.v1.12.0.clusterserviceversion.yaml
Labels: approved, size/XS

#89 increment operator version
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.13.0/ibm-monitoring-prometheus-operator-ext.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.13.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/ibm-monitoring-prometheus-operator-ext.package.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#86 Issue #38842 - Set imagePullPolicy to IfNotPresent
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.13.0/ibm-monitoring-prometheus-operator-ext.v1.13.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#90 crd v1 changes
  deploy/crds/monitoring.operator.ibm.com_prometheusexts_crd.yaml
  deploy/olm-catalog/ibm-monitoring-prometheus-operator-ext/1.13.0/monitoring.operator.ibm.com_prometheusexts_crd.yaml
Labels: approved, size/XXL

#91 change qemu version
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS
